#!/usr/bin/env python2
import rospy
from rospy_minimal.talker import Talker


if __name__ == '__main__':
    rospy.init_node('talker_node')

    # get parameters
    talk_topic = rospy.get_param('~talk_topic', 'talk')
    listen_topic = rospy.get_param('~listen_topic', 'listen')

    # create Talker object and run node
    talker = Talker(talk_topic, listen_topic)
    while not rospy.is_shutdown():
        talker.talk()
        rospy.sleep(1.0)    # sleep for 1 second
